// Auth Types
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CLEAR_CHANGE_PASSWORD = "CLEAR_CHANGE_PASSWORD";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Members Types
export const GET_MEMBERS = "GET_MEMBERS";
export const ADD_MEMBER = "ADD_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_MEMBER = "UPDATE_MEMBER";
export const FILTER_MEMBERS = "FILTER_MEMBERS";
export const CLEAR_MEMBERS = "CLEAR_MEMBERS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const MEMBER_ERROR = "MEMBER_ERROR";
export const SET_ONSCREEN_MEMBERS = "SET_ONSCREEN_MEMBERS";
export const CLEAR_ONSCREEN_MEMBERS = "CLEAR_ONSCREEN_MEMBERS";
export const CLEAR_MEMBER_ERROR = "CLEAR_MEMBER_ERROR";
